# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import comment_scam_detector_pb2 as comment__scam__detector__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in comment_scam_detector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScamDetectionServiceStub(object):
    """Service definition for detecting scams in comment threads
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectScam = channel.unary_unary(
                '/comment_scam_detector.ScamDetectionService/DetectScam',
                request_serializer=comment__scam__detector__pb2.ScamDetectionRequest.SerializeToString,
                response_deserializer=comment__scam__detector__pb2.ScamDetectionResponse.FromString,
                _registered_method=True)


class ScamDetectionServiceServicer(object):
    """Service definition for detecting scams in comment threads
    """

    def DetectScam(self, request, context):
        """Detects if a comment thread contains a scam
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScamDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectScam': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectScam,
                    request_deserializer=comment__scam__detector__pb2.ScamDetectionRequest.FromString,
                    response_serializer=comment__scam__detector__pb2.ScamDetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comment_scam_detector.ScamDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('comment_scam_detector.ScamDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScamDetectionService(object):
    """Service definition for detecting scams in comment threads
    """

    @staticmethod
    def DetectScam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/comment_scam_detector.ScamDetectionService/DetectScam',
            comment__scam__detector__pb2.ScamDetectionRequest.SerializeToString,
            comment__scam__detector__pb2.ScamDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
